# Generated by Django 4.1.5 on 2023-01-19 16:59

from django.db import migrations, models
import django.db.models.deletion
import news_feed.models


class Migration(migrations.Migration):

    dependencies = [
        ("news_feed", "0001_create_page_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news_feed.page"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
            bases=(models.Model, news_feed.models.DateTimeMixin),
        ),
    ]
